version: '3.8'

services:
  nginx-network1:
    image: nginx:latest
    container_name: nginx-net1
    networks:
      - network1
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

  nginx-network2:
    image: nginx:latest
    container_name: nginx-net2
    networks:
      - network2
    ports:
      - "8082:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    restart: always

networks:
  network1:
    driver: bridge
    name: network1

  network2:
    driver: bridge
    name: network2